site_name: NISO FASTEN Working Group - Recommended Standards

title: NISO
email: 
description: NISO
baseurl: /niso-econtent-standards/
url: https://mdovey.github.io
highlight: rouge
copyright: James King

    
remote_theme: chromatical/jekyll-materialdocs

