site_name: NISO FASTEN Working Group - Recommended Standards
title: MaterialDocs
email: hello@chromaticaldesign.com
description: A demo site for the Jekyll MaterialDocs theme.
baseurl: "/jekyll-materialdocs" # the subpath of your site, e.g. /blog
url: "https://chromatical.github.io" # the base hostname & protocol for your site, e.g. http://example.com
highlight: rouge
copyright: James King    
remote_theme: chromatical/jekyll-materialdocs

